# Generated by Django 2.2.1 on 2019-05-26 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ip',
            field=models.GenericIPAddressField(default=None),
            preserve_default=False,
        ),
    ]
