# Generated by Django 2.2.1 on 2019-05-26 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_profile_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ip',
        ),
    ]
